playbooks/monitoring/roles/grafana/tasks/main.yml
we did not enable it and it might fail as epel might be not installed
at all on the machine
=> don't disable epel in grafana role

playbooks/monitoring/roles/graphite/tasks/main.yml
the file does not exist after the installation, and thus the previous
logic skiped the task on fresh installs
=> run setup-graphite-db.exp only when graphite.db did not exist yet

playbooks/satellite/roles/satellite-populate/tasks/main.yaml
Check if the manifest is already present and upload it the condition evaluates to true
=> Fix the failing upload manifest while populating satellite

playbooks/satellite/roles/docker-host/tasks/main.yaml, playbooks/satellite/roles/satellite-populate/tasks/main.yaml
Added support for cleaning up Overlay FS configurations and volume groups
The commits adds the following tasks:
- Checks if the overlay was already configure
- Unmounts the path at which overlay was mounted
- Cleans up /etc/fstab
- Removes the volume group associated with overlay
Addresses #24
=> Add support for Overlay FS cleanup

playbooks/satellite/roles/client-scripts/files/clients.yaml.j2
Previously, if the package wasn't installed or no lower versions were available, the task failed
The commit addresses this issue and handles the failure more gracefully
=> Don't fail during downgrade if the package is not installed

playbooks/satellite/roles/docker-host/tasks/main.yaml
If docker is already installed on the remote machine, we should not fail.
The commit addresses this issue by checking whether there was some version of docker which was already installed and if found removes it.
=> Don't fail docker-host if docker is already installed

playbooks/satellite/docker-tierdown.yaml
docker-tierdown should also cleanup ssh known_hosts so as to prevent from ssh authentication errors
=> docker-tierdown should also cleanup ssh known_hosts

requirements.txt
Ansible version 1.9.x doesn't have support for include + with_items, Ansible 2.2 brings it back
Update requirements.txt to support Ansible 2.2
=> Update requirements for ansible 2.2

playbooks/satellite/docker-tierdown.yaml
Sometimes, if the containers are interrupted they might be holding some active network connection
This prevents docker service from restarting normally
PR adds a task into docker-tierdown.yaml to clear up these active network connections
=> Clearup docker active network connections

ansible.cfg
The PR makes the following changes:
- Fix support for systems with long hostnames
- Increase the SSH ControlPersist to improve upon performance
- Increase the default number of forks ansible uses from 5 to 10
- Disable host key checking while executing playbooks
- Sets the default inventory file to conf/hosts.ini
=> Add customizations to ansible behaviour

conf/satperf.yaml, playbooks/satellite/capsules.yaml, playbooks/satellite/installation.yaml, playbooks/satellite/roles/capsule/tasks/main.yaml, playbooks/satellite/roles/rhsm-satellite/tasks/main.yaml
1) Added new variables base_capsule_pool, sat_version and
extend_root_partition to satperf.yaml file.
2) All the new variables default values  are set/configured for sat6.2
and satperf setups.
3) Make extend root partition optional
4) Added a fix for the BZ 1458749
5) Introduced base_capsule_pool as every manifest may not have,
'Employee SKU' and via rhsm-satellite task we are enabling,
the pool rhsm_pool, which is "Employee SKU".
=> Changed and Update miscellaneous stuff.

conf/satperf.yaml, playbooks/satellite/roles/grafana-graph-download/tasks/main.yaml, playbooks/tests/registrations.yaml, playbooks/tests/roles/grafana-graph-download/tasks/main.yaml
We need to understand a number of metrics after our experiment finishes the run
These changes allow us to automate the downloading of the different graphs from grafana and save them
=> Automate the downloading of the grafana graphs after our experiment runs

playbooks/satellite/roles/remove-home-extend-root/tasks/extend_root_partition.yaml, playbooks/satellite/roles/remove-home-extend-root/tasks/remove_home_partition.yaml
This patch should make a better use of native Ansible modules for removing and resizing LVM LV's, and make it more deterministic. Only uncertainity is name of the root and home LVs. We rely on these being named root and home or lv_root and lv_home. If not, this is not going to work reliably.
=> Better detection of LV and VG names

playbooks/common/roles/scalelab-nic-cleanup/tasks/main.yaml, playbooks/common/roles/scalelab-nic-cleanup/templates/ifcfg-ethx.j2
Original version of this role relied on the interface file for private_nic already present. That may be the case when installing on perflab machines, but when installing on a local virtual machine with the interface file not yet created this may cause fail during the playbook run. This pull request creates the file if not present and fill it out with correct address info. If the file already exists, it will check and add the required information just like in the original version.
=> Create the private nic interface file if not present

playbooks/common/roles/rhsm/tasks/main.yaml
Use the redhat_subscription Ansible module for the RHSM registration. According to comments in the file this wasn't reliable in the past, but should be fixed in the recent version on Ansible.
=> Use redhat_subscription module for the registration

playbooks/satellite/roles/setup/tasks/main.yaml
Solves #82 Attaching to pool fails when the querying variable is empty.
=> Dealing with "querying" when null

playbooks/kvm-hosts/cleanup.yaml
This PR extracts names of VMs in the configuration, and removes only these, not all VMs on the KVM host.
=> Delete only OUR VMs on cleanup.

run-library.sh
We need to be able to differentiate between run-{bench,puppet,...} runs to filter out specific instances of runs in ELK.
=> Add bench run id as a parameter

playbooks/tests/some-webui-pages.yaml
The playbook is failing due to the following error :
ERROR! Syntax Error while loading YAML.
did not find expected key
The error appears to be in '/home/jenkins/agent/workspace/ContPerf67/playbooks/tests/some-webui-pages.yaml': line 33, column 9, but may
be elsewhere in the file depending on the exact syntax problem.
The offending line appears to be:
'h1[^>]\+>\s\+Job invocations\s\+</h1'
- uri: ''
^ here
=> remove/comment'h1[^>]\+>\s\+Job invocations\s\+</h1' line

conf/satperf.yaml, playbooks/common/prepare_host.yaml, playbooks/external_dbs/setup.yaml, playbooks/katello/installation.yaml, playbooks/katello/katello_ci_installation.yaml, playbooks/katello/katello_mirror_installation.yaml, playbooks/katello/katello_nightly_installation.yaml, playbooks/katello/katello_stable_installation.yaml, playbooks/katello/katello_stable_installation_3.14.yaml, playbooks/satellite/capsules.yaml, playbooks/satellite/installation.yaml
Replace the code that deals with NTP management with the `timesync`
Linux system role (available as well in RHEL System Roles).
This change will require to install the role as a dependency, and it takes
a bit more time to run, but in my opinion it's better to rely on a
> stable and consistent configuration interface to automate and manage
> multiple releases of Red Hat Enterprise Linux
As stated in [1].
[1] https://access.redhat.com/articles/3050101
=> linux-system-roles: Replace NTP code with timesync role

README.md, playbooks/common/roles/common/tasks/main.yaml, playbooks/satellite/roles/capsule/tasks/main.yaml, playbooks/satellite/roles/setup/tasks/main.yaml
Replace the code that deals with firewalling (disabling it entirely) with
the `firewall` Linux system role (not available yet in RHEL Sytem Roles)
and document it accordingly, setting the needed rules for proper
Satellite and Capsule communication.
=> linux-system-roles: Replace firewalling code with firewall role

conf/satperf.yaml, playbooks/common/roles/partition-new-storage/tasks/main.yaml, playbooks/satellite/installation.yaml, requirements.yml
Provide a way to store most of the Satellite data in a different
disk.
To do so, set `partition_new_storage` to `True` and `storage_pools_disk`
with the value of the disk to be used, and a new VG and the required
LV and partitions will be created.
It uses the `linux-system-roles.storage` Ansible role.
Note: this code can be easily reused to implement the same funcionality
for capsules installations.
=> Allow the usage of an additional disk to store Satellite data

playbooks/satellite/capsules.yaml
Extend the work done in https://github.com/redhat-performance/satperf/commit/344d54f1b8a92083a12d997e2c25dc245c0926f8
to be able to provide an additional disk to store capsule's data
(adapting the set of partitions to capsule's needs).
=> Allow the usage of an additional disk to store capsule's data

playbooks/satellite/roles/setup/tasks/main.yaml
Enable the `satellite:el8` module as required by the documentation.
=> main.yaml: Replace workaround with proper solution

playbooks/satellite/capsules.yaml
In the case of not being able to rely on DNS resolution, we better
have a working /etc/hosts file as soon as possible (to register against
the Satellite server, for example).
=> capsules.yaml: Move roles that configure networking and resolution

playbooks/satellite/roles/capsule/tasks/main.yaml
Enable the `satellite-capsule` module as required by the documentation.
=> roles/capsule: Enable satellite-capsule module if needed

playbooks/satellite/installation.yaml
In the case of not being able to rely on DNS resolution, we better
have a working /etc/hosts file as soon as possible (not with the same
intentions as in https://github.com/redhat-performance/satperf/pull/194,
but desirably anyway).
=> installation.yaml: Move roles that configure networking and resolution

playbooks/satellite/roles/capsule-location/tasks/main.yaml
In order to do that, a new `location=MyLocation` can be provided
in the inventory entry for the capsule.
Otherwise, the default `'Location for ' + inventory_hostname` will be used.
=> roles/capsule-location: Add ability to provide Location to capsule

conf/satperf.yaml, playbooks/satellite/capsules.yaml, playbooks/satellite/installation.yaml
The default will be to configure it, but if it's  desired not to do so, please set:
```
configure_plain_network: False
```
in the `satperf.local.yaml` configuration file
=> feat: Add ability to only configure plain network when needed

README.md, playbooks/common/roles/plain-network/tasks/main.yaml, requirements.yml
The ipaddr() filter migrated to the ansible.utils collection.
=> roles/plain-network: Fix ipaddr() filter deprecation warning

playbooks/satellite/capsules.yaml, playbooks/satellite/installation.yaml
If we pass storage_pools as parameter we can safely assume that we want to overwrite any existing label.
=> satellite/capsule: Set storage_safe_mode to False when providing storage_pools

playbooks/common/roles/common/tasks/main.yaml
In order to do so:
- Create a `public_ip=` parameter in the inventory file
=> common/main.yaml: Add ability to use set public IPs in /etc/hosts

playbooks/satellite/roles/capsule/tasks/main.yaml
In order to do so, add a `rex_mode=mqtt` property to the capsule entry in the inventory
=> roles/capsule: Configure MQTT REX mode when set

playbooks/satellite/clients_host-registration.yaml, playbooks/satellite/host-registration_generate-command.yaml, playbooks/satellite/roles/client-scripts/files/clients_host-registration.yaml.j2, playbooks/satellite/roles/client-scripts/tasks/main.yaml, playbooks/tests/registrations.yaml
This code can be tested the following way:
- Create the registration commands for each capsule (Satellite included):
`playbooks/satellite/host-registration_generate-command.yaml -e "ak=${YOUR_ACTIVATION_KEY}"'
`
- Register the content hosts:
`playbooks/tests/registrations.yaml -e "method=clients_host-registration"
`
=> feat: Add new registration method: 'clients_host-registration'

playbooks/satellite/roles/capsule/tasks/main.yaml
Retrying the configuration after a failure can hide a misconfigured capsule and lead to duplicated host entries.
=> fix: capsule: Fail hard if capsule configuration fails

scripts/investigate-regs-errors.py
These tools are served publicly on github.  Small update in the comments to use example.com instead of actual hostnames internal that are meaningless generically speaking to the greater internet at large.
=> obfuscate internal hostnames

experiment/run-library.sh
I want to have the status data file available (with the gathered measurements) without the need to push the data to ES or RP.
The drawback is that we unconditionally add 45-60s execution time per test when `$skip_measurement != true` (mostly set in `full.sh`).
=> feat(experiment/run-library.sh): Upload results iff `GOLDEN`
