satperf.sh, scripts/docker-registration.sh
=> fixes #3 - (WIP) update pbench commands to latest versons

playbooks/monitoring/grafana.yaml, playbooks/monitoring/graphite.yaml, playbooks/monitoring/roles/collectd-generic/tasks/main.yml, playbooks/monitoring/roles/grafana/tasks/main.yml, playbooks/monitoring/roles/graphite/tasks/main.yml
this expects the packages are available in some local repo
=> add offline install support

playbooks/satellite/10gnic.yaml, playbooks/satellite/docker-tierdown.yaml, playbooks/satellite/roles/check-10g/tasks/main.yaml
The patch adds functionality to find NICs which support 10g connection
=> [WIP] Add functionality for 10G NIC detection

playbooks/satellite/capsules.yaml, playbooks/satellite/docker-tierdown.yaml, playbooks/satellite/installation.yaml
Removed pbench specific roles from satellite playbooks
=> We don't use pbench anymore.

conf/satperf.yaml, playbooks/tests/registrations.yaml
=> Provide a way to specify where to reach grafana

playbooks/satellite/docker-host-atomic.yaml, playbooks/satellite/roles/atomic-image-build/files/Dockerfile, playbooks/satellite/roles/atomic-image-build/tasks/main.yaml, playbooks/satellite/roles/atomic-package-install/tasks/main.yaml, playbooks/satellite/roles/docker-host-atomic/tasks/main.yaml
=> [WIP] Let's go atomic

playbooks/satellite/roles/scalelab-nic-cleanup/tasks/main.yaml
=> Add NIC cleanup for R620

playbooks/satellite/docker-tierup.yaml, playbooks/satellite/roles/docker-host/files/Dockerfile
=> [Needs Testing]Move to systemd based containers

README.md, playbooks/satellite/roles/capsule-populate/tasks/main.yaml, playbooks/satellite/roles/client-content/tasks/main.yaml, playbooks/satellite/roles/satellite-populate/tasks/main.yaml
*) Added to capsule-populate, client-content and satellite-populate
roles.
=> Added few more async and non-async tags for syncing content option

conf/satperf.yaml
We need to understand a number of metrics after our experiment finishes the run
These changes allow us to automate the downloading of the different graphs from grafana and save them
=> Fix a typo

playbooks/satellite/roles/docker-host/tasks/main.yaml
=> Handle the umounting of the paritions properly while configuring overlayfs

playbooks/satellite/roles/satellite-populate/tasks/main.yaml
=> Support Puppet 5

conf/satperf.yaml
=> Enable the rhel extras rpms repo due to an ansible dependency

README.md
Changed instructions for installing docker hosts
=> Updated Readme.md for playbook instructions.

playbooks/docker/docker-tierdown.yaml
Fixed state of "Start docker daemon" task.
Closes #99
=> Updated docker-tierdown.yaml

playbooks/satellite/installation.yaml, playbooks/satellite/roles/enable-remote-exec-by-ip/tasks/main.yaml
Closes #61 
Signed-off-by: T K Sourab <sourabhtk37@gmail.com>
=> Added role to enable Remote execution by IP

playbooks/satellite/roles/client-content/tasks/main.yaml
Closes #102 
Domains gets assigned location while creation.
Signed-off-by: T K Sourab <sourabhtk37@gmail.com>
=> Added fix for #102: Domain not assigned a Location.

playbooks/katello/katello_nightly_installation.yaml
Reference: https://theforeman.org/plugins/katello/nightly/installation/index.html
=> Katello nightly installation for CentOS & RHEL

playbooks/katello/katello_nightly_installation.yaml
Changed this 
with_items:
yum -y localinstall https://yum.theforeman.org/releases/nightly/el7/x86_64/foreman-release.rpm
TO
with_items:
- yum -y localinstall https://yum.theforeman.org/releases/nightly/el7/x86_64/foreman-release.rpm
=> Updated the file.

playbooks/katello/katello_nightly_installation.yaml
In order to solve the below error - 
/Stage[main]/Foreman_proxy::Register/Foreman_smartproxy[gprfc027.sbu.lab.eng.bos.redhat.com]: 
Could not evaluate: Proxy gprfc027.sbu.lab.eng.bos.redhat.com cannot be retrieved: unknown error (response 500)
=> made a entry in /etc/hosts file with IP and hostname

experiment/download-test.sh, playbooks/tests/downloadtest.yaml
- syntax correction of adding down_test_repo subscription to activation key
- set -e to exit if hammer job-invocation doesn't work
=> Correct issues with download test

experiment/download-test.sh, playbooks/tests/downloadtest.yaml
Also make code easy to understand
=> Solve errors with download test

experiment/download-test.sh, playbooks/tests/downloadtest.yaml
- Replace shell command rm -rf with find and files module in playbook
- Missed a $ using variable name
=> Download test playbook change

experiment/download-test.sh, playbooks/tests/downloadtest-syncrepo.yaml, playbooks/tests/downloadtest.yaml
- Combine all download test commands to single playbook
- Modify download test to be able to work on multiple repos
=> Download test for multiple repos

experiment/download-test.sh, playbooks/tests/downloadtest-syncrepo.yaml
Issue passing string with a space to playbook
=> Fix issue with download test playbook

experiment/util-reg.sh
make PARAM_all_rex=true in doit.sh to rex date, subscription-manger refresh, sleep 300 via both ssh and ansible
=> Add parameter to automate rex commands

experiment/download-test.sh, playbooks/tests/downloadtest.yaml, playbooks/tests/files/wait-for-job.py
@jhutar please squash and merge
=> Fix download test automation

playbooks/satellite/installation.yaml
Update the ones for >= 6.10 and add the ones for <= 6.9.
=> Update Satellite storage requirements

playbooks/satellite/roles/capsule-location/tasks/main.yaml, playbooks/satellite/roles/puppet-autosign/tasks/main.yaml
"7.0 is dead, long live 6.11!"
=> Change version checks looking for 7.0

experiment/debug-full-skip-to-reg.sh, experiment/full.sh, experiment/pg_repack.sh, experiment/rex.sh
- Removed all the version checks for not supported versions
- Add a forgotten wait while at it
- Fix a typo ;)
=> cleanup: Cleanup version checks in experiment/ 

playbooks/satellite/capsules.yaml
To unify as much code as possible with Satellite.
=> capsules.yaml: Add upgrade-restart role

playbooks/satellite/installation.yaml
To ease diffing with capsules code.
=> installation.yaml: Remove EC2 commented code

playbooks/satellite/roles/capsule/tasks/main.yaml
=> roles/capsules: Record capsule installer duration as well

conf/satperf.yaml, playbooks/satellite/capsules.yaml, playbooks/satellite/installation.yaml
This will give us some flexibility until some needed ports are added to the services (MQTT port, wink, wink)
=> feat: Move firewall rules definition to configuration file

playbooks/satellite/subnet-create.yaml
It will create the subnet that a host (Satellite or capsules) is connected to.
=> feat: Add a subnet-create playbook

scripts/get-task-fuzzy-duration.py
Instead of waiting an arbitrary amount of time, look for tasks that doesn't seem to progress in a certain amount of time (in this case: 10 minutes).
=> fix: scripts/get-task-fuzzy-duration.py: Account for long running tasks

ansible.cfg, experiment/full.sh, experiment/run-library.sh, playbooks/tests/includes/manifest_test.yaml, playbooks/tests/manifest_test.yaml, playbooks/tests/manifest_test_download.yaml, playbooks/tests/manifest_test_reimport.yaml
Add replacement for 'Prepare for Red Hat content' code with Foreman Ansible modules.
Change the tooling accordingly to measure duration of plays/tasks properly.
- Fixes: https://issues.redhat.com/browse/SAT-32641
=> POC for Foreman Ansible modules

experiment/full.sh
Co-developed-by: Imaanpreet Kaur <ikaur@redhat.com>
Tested by : Pablo
=> feat(experiment/full.sh): Add basic Flatpak content support
